version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: als_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ALS_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: als_backend
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - ollama
    networks:
      - ALS_network

  postgres:
    image: postgres:15-alpine
    container_name: als_postgres
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ALS_network

  ollama:
    image: ollama/ollama:latest
    container_name: als_ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
      - ./back/ai:/models
    networks:
      - ALS_network

networks:
  ALS_network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
